# version 3의 의미는 3으로 시작하는 최신 버전을 사용한다.
version: "3"

# 실행하려는 컨테이너를 정의한다. 컴포즈에서는 컨테이너 대신 서비스라는 개념을 사용한다.
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    # db 서비스에서 사용할 도커 이미지를 넣는다. 여기서는 docker hub의 공식 postgres 이미지를 사용한다.
    image: postgres:12.2
    volumes:
      # docker run 으로 db 컨테이너를 실행할 때 와 마찬가지로 프로젝트 루트 아래에 데이터 저장?
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tpay
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data: